#spring.application.name=EpiMap
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-334f3h-kr.vpc-pub-cdb.ntruss.com:3306/EpiMap?serverTimezone=Asia/Seoul
    username: meditrackers
    password: bitcamp!@#123

# file_size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB	

#mybatis setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations: 
  - /mapper/**/*.xml
server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mypassword
    key-store-type: PKCS12
    key-alias: mysslkey